// HISTORY OF HTML

// RUNOFF
// GML AND SCRIBE
// SGML
// HTML

// JAVASCRIPT SAVED HTML

// DOM , THE BROWSER'S API

// PLACE CSS LINK TAG AS HIGH IN THE HEAD AS POSSIBLE.

// DOCUMENT.TREE STRUCTURE

// FAVOR CLEAN CODE AND EASY MAINTENANCE

// ONLY FAVOR PERFORMANCE IN EXTREME CASES

// INPUT EVENTS

// BLUR, CHANGE, FOCUS, KEYDOWN, KEYPRESS, KEYUP,
// RESET, SUBMIT

// CANCEL BUBBLING

// EVENT.STOPPROPAGATION();

// EVENT.PREVENTDEFAULT();


// PERFORMANCE

// TRYING TO OPTIMIZE WITHOUT GOOD PERFORMANCE DATA IS A WASTE OF TIME

// AJAX LIBRARIES

// DIVISION OF LABOR