// NODE JS

// OPEN SOURCE RUNTIME
// BUILT ON CHROME'S V8 JS ENGINE

// CAN CREATE ANYTHING A SCRIPTING OR SERVER LANGUAGE LIKE PYTHON,
// OR RUBY CAN, BUT WITH JAVASCRIPT (COMES WITH TRADEOFFS SOMETIMES)

// TOOLING (BUILD, AUTOMATION, ETC)
// API'S (REST, REALTIME, ETC)
// CDNs
// SHAREABLE LIBRARIES
// DESKTOP APPLICATIONS
// INTERNET OF THINGS
// LOTS OF OTHER THINGS